package main

import (
	"log"
	"net/http"

	_ "shelke.dev/api/docs" // docs is generated by Swag CLI, you have to import it.
	"shelke.dev/api/internal/adapters/db"
	httphandler "shelke.dev/api/internal/adapters/http"
	"shelke.dev/api/internal/core/services"
)

// @title Portfolio API
// @version 1.0
// @description This is the API for the Portfolio project.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /
func main() {
	dbQueries, pool, err := db.NewDB()
	if err != nil {
		log.Fatalf("Could not initialize database: %v", err)
	}
	defer pool.Close()

	healthCheckService := services.NewHealthCheckService()
	server := httphandler.NewServer(healthCheckService, dbQueries)
	server.Use(httphandler.LoggingMiddleware)

	log.Println("Server starting on port 8080...")
	if err := http.ListenAndServe(":8080", server); err != nil {
		log.Fatalf("Could not start server: %v", err)
	}
}
